### Listar os funcionários
GET https://localhost:5001/api/funcionario/listar

### Cadastrar um funcionário
POST https://localhost:5001/api/funcionario/cadastrar
Content-Type: application/json

{
    "nome" : "Diogo Steinke Deconto",
    "cpf" : "123456789"
}

### Buscar um funcionário pelo CPF
GET https://localhost:5001/api/funcionario/buscar/123456789

### Deletar um funcionário pelo CPF
DELETE https://localhost:5001/api/funcionario/deletar/123456789

### Alterar um funcionário
PATCH  https://localhost:5001/api/funcionario/alterar
Content-Type: application/json

{
    "nome" : "Diogo Steinke Deconto Modificado",
    "cpf" : "123456789"
}