### Listar os funcionários
GET https://localhost:5001/api/funcionario/listar

### Cadastrar um funcionário
POST https://localhost:5001/api/funcionario/cadastrar
Content-Type: application/json

{
    "nome" : "José",
    "cpf" : "12312312312",
    "email" : "asd@asd.com",
    "salario" : 1000,
    "nascimento" : "1900-09-20"
}

### Buscar um funcionário pelo CPF
GET https://localhost:5001/api/funcionario/buscar/1234567891

### Deletar um funcionário pelo Id
DELETE https://localhost:5001/api/funcionario/deletar/4

### Alterar um funcionário
PATCH  https://localhost:5001/api/funcionario/alterar
Content-Type: application/json

{
    "id" : 5,
    "nome" : "Diogo Steinke Deconto Modificado Teste",
    "cpf" : "123456789"
}